name: sms_auto_fill_widget
description: SMS Autofill Textbox Widget
version: 0.0.1
homepage: https://github.com/william-waiyanhtat/sms_autofill_widget

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  sms_autofill: ^1.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

